    - name: copy key
      become: true
      ansible.posix.authorized_key:
        user: "{{control_node_user}}"
        state: present
        key: "{{ansible_ssh_private_key_file_lookup}}"
  
    - name: disable Password Authentication
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        insertafter: '^#PasswordAuthentication '
        line: PasswordAuthentication no

    - name: Stop and Start ssh
      become: true
      service:
        name: ssh
        state: restarted