# following https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
    - name: Install aptitude
      become: true
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - acl
          - unzip
          - borgbackup
          - zfsutils-linux
          - cron
          - powertop
          - smartmontools
          - rsync
          - hdparm
          - postfix
          - mailutils
          - python-is-python3
          - jq
        state: latest
        update_cache: true

    - name: Install pips
      become: true
      ansible.builtin.pip:
        name: borgmatic

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      become: true
      pip:
        name: docker

    - name: Install required system packages
      become: true
      apt:
        pkg:
          - docker-compose
        state: latest
        update_cache: true