# https://www.redhat.com/sysadmin/ansible-automate-updates-home
  - name: Update all installed packages using APT module
    become: true
    apt:
      name: '*'
      state: latest
      update_cache: yes
      only_upgrade: yes
    register: apt_update_status

  - name: Remove packages not needed anymore
    become: true
    apt:
      autoremove: yes