  - name: Ensure the luks key is in place "{{luks.key_location}}"
    become: true
    template:
      src: "{{control_node.luks_key_location}}"
      dest: "{{luks.key_location}}"
      backup: true
      mode: 0400

  - name: Create LUKS container (remains unchanged if it already exists)
    become: true
    community.crypto.luks_device:
     device: "{{luks.device_id}}"
     state: "opened"
     name: "{{luks.mapper_name}}"
     keyfile: "{{luks.key_location}}"
     type: luks2
    when:
      - setup_luks | bool
     
  - name: Create a ext4 filesystem on /dev/mapper/{{luks.mapper_name}}
    become: true
    community.general.filesystem:
      fstype: ext4
      dev: "/dev/mapper/{{luks.mapper_name}}"
    when:
      - setup_luks | bool