
  - name: Ensure the luks key is in place "{{luks.key_location}}"
    become: true
    template:
      src: "{{local_luks_key_location}}"
      dest: "{{luks.key_location}}"
      backup: true
      mode: 0400

  - name: Replace a localhost entry searching for a literal string to avoid escaping
    become: true
    ansible.builtin.lineinfile:
      path: /etc/crypttab
      search_string: '{{luks.mapper_name}}'
      line: "{{luks.mapper_name}}      ID={{luks.device_id}}      {{luks_key_location}}   luks"

  - name: Ensure mountpoint exists
    become: true
    file:
      path: /backup
      state: directory
      mode: 0700

  - name: Replace a localhost entry searching for a literal string to avoid escaping
    become: true
    ansible.builtin.lineinfile:
      path: /etc/fstab
      search_string: '{{luks.mapper_name}}'
      line: "/dev/mapper/{{luks.mapper_name}}  {{luks.mountpoint}} ext4"