
  - name: Add the user bookstack
    become: true  
    ansible.builtin.user:
      name: "{{usernames.bookstack}}"
      comment: bookstack docker user
      uid: 1040
      group: docker

  - name: Create folder {{dockerpath}}/bookstack
    become: true
    ansible.builtin.file:
      path: "{{dockerpath}}/bookstack"
      state: directory
      owner: "{{usernames.bookstack}}"  
      group : docker 

  - name: create subfolders
    become: true
    become_user: "{{usernames.bookstack}}"
    ansible.builtin.file:
      path: "{{item.src}}"
      state: directory
      #mode: '0755'
    loop:
      - {src: "{{dockerpath}}/bookstack/backup"}
      - {src: "{{dockerpath}}/bookstack/config"}
      

  - name: Ensure docker compose config in place
    become: true
    become_user: "{{usernames.bookstack}}"
    template:
      src: ../templates/bookstack_docker_compose.j2
      dest: "{{ app_bookstack.docker_compose_target }}"
      backup: true
      mode: 0640

  - name: Pull bookstack image
    become: true
    become_user: "{{usernames.bookstack}}"
    community.docker.docker_image:
      name: lscr.io/linuxserver/bookstack
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
      pull:
        platform: amd64

  - name: Create a network net_bookstack
    become: true
    become_user: "{{usernames.bookstack}}"
    docker_network:
      name: net_bookstack  

  - name: Add a container to a network
    become: true
    become_user: "{{usernames.bookstack}}"
    docker_network:
      name: net_bookstack
      connected:
        - proxy
        - nginx_web_1

  - name: Pull mariadb image
    become: true
    become_user:  "{{usernames.bookstack}}"
    community.docker.docker_image:
      name: lscr.io/linuxserver/mariadb
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.
      pull:
        platform: amd64

  - name: deploy Docker Compose stack
    become: true
    become_user:  "{{usernames.bookstack}}"
    community.docker.docker_compose:
      project_src: "/home/{{usernames.bookstack}}"
      files:
      - docker-compose.yml

  - name: Ensure the database backup script is inplace
    become: true
    become_user:  "{{usernames.bookstack}}"
    template:
      src: ../templates/bookstack_db_backup.j2
      dest: "{{dockerpath}}/bookstack/db_backup.sh"
      backup: true
      mode: 0750

  - name: schedule a database backup every night
    become: true      
    ansible.builtin.cron:
      name: "check dirs"
      minute: "0"
      hour: "3"
      job: "{{dockerpath}}/bookstack/db_backup.sh"
      cron_file: ansible_bookstack
      user: root
      