
- name: Add the user wekan
  become: true  
  ansible.builtin.user:
    name: "{{usernames.wekan}}"
    comment: wekan docker user
    uid: 1260
    group: docker

- name: Create folder {{dockerpath}}/wekan
  become: true
  ansible.builtin.file:
    path: "{{dockerpath}}/wekan"
    state: directory
    owner: "{{usernames.wekan}}"  
    group : docker 

- name: Create a network net_wekan
  become: true
  become_user: "{{usernames.wekan}}"
  docker_network:
    name: net_wekan

- name: Ensure docker compose config in place
  become: true
  become_user:  "{{usernames.wekan}}"
  template:
    src: ../templates/wekan_docker_compose.j2
    dest: "{{ app_wekan.docker_compose_target }}"
    backup: true
    mode: 0640


- name: deploy Docker Compose stack
  become: true
  become_user:  "{{usernames.wekan}}"
  community.docker.docker_compose:
    project_src: "/home/{{usernames.wekan}}"
    files:
     - docker-compose.yml 

- name: Create symbolic link 
  become: true
  file:
    src:  "{{zfs.pool_mountpoint}}/docker/wekan/data"
    dest: "{{zfs.pool_mountpoint}}/samba/wekan"
    state: link