    - name: create folders
      become: true
      ansible.builtin.file:
        path: "/etc/borgmatic"
        state: directory
        mode: 600

    - name: Ensure group {{borgmatic.group}} exists
      become: true
      ansible.builtin.group:
        name: "{{borgmatic.group}}"
        state: present

    - name: create folders "{{luks.mountpoint}}"
      become: true
      ansible.builtin.file:
        path: "{{luks.mountpoint}}"
        state: directory
        owner: root
        group: "{{borgmatic.group}}"
        mode: 750



    - name: Ensure borgmatic config in place
      become: true
      template:
        src: ../templates/borgmatic_config.j2
        dest: "/etc/borgmatic/config.yaml"
        backup: true
        mode: 0640

    - name: Initialize an empty borg repository
      become: true      
      command: "borgmatic init --encryption repokey"

    - name: schedule borgmatic every night
      become: true      
      ansible.builtin.cron:
        name: "check dirs"
        minute: "00"
        hour: "4"
        job: "/usr/local/bin/borgmatic"
        cron_file: ansible_borgmatic
        user: root
        
    - name: provide borg password file
      become: true
      template:
        src: ../templates/borg_password.j2
        dest: "{{borgmatic.password_file}}"
        backup: true
        mode: 0400

    - name: Placing a custom borg log path in /etc/environment
      become: true
      ansible.builtin.lineinfile:
        path: /etc/environment
        search_string: 'ANS_BORG_LOG'
        line: 'ANS_BORG_LOG="{{borgmatic.custom_log_file}}"'

    - name: copy script to check the recent borg backups
      become: true
      template:
        src: ../templates/scripts/check_borg_run.j2
        dest: "{{script_location}}/ans_check_borg_run.sh"
        backup: true
        mode: 0540

    - name: schedule daily check of borg backup
      become: true      
      ansible.builtin.cron:
        name: "check dirs"
        minute: "45"
        hour: "06"
        job: 
          "{{script_location}}/ans_check_borg_run.sh {{control_node.email}} >> $ANS_BORG_LOG"
        cron_file: ansible_check_borg_run
        user: root
