
  - name: copy script that logs smart values
    become: true
    template:
      src: ../templates/scripts/log_smart_values.j2
      dest: "{{script_location}}/ans_log_smart_values.sh"
      backup: true
      mode: 0540


  - name: create script that returns last smart test
    become: true
    template:
      src: ../templates/scripts/get_smart_test_result.j2
      dest: "{{script_location}}/ans_get_smart_test_result.sh"
      backup: true
      mode: 0540

  - name: copy script to evaluate smart values
    become: true
    template:
      src: ../templates/scripts/hdd_report_evaluate.j2
      dest: "{{script_location}}/ans_hdd_report_evaluate.py"
      backup: true
      mode: 0540

  - name: Install pandas python package
    become: true
    ansible.builtin.pip:
      name: pandas

  - name: schedule daily evaluation of SMART logs
    become: true      
    ansible.builtin.cron:
      name: "check dirs"
      minute: "55"
      hour: "23"
      job: 
        python "{{script_location}}/ans_hdd_report_evaluate.py"
      cron_file: ansible_hdd_evaluate_smart_values
      user: root


  - name: copy script to trigger SMART long tests to "{{script_location}}/ans_smart_long_test.sh"
    become: true
    template:
      src: ../templates/scripts/schedule_smart_long_test.j2
      dest: "{{script_location}}/ans_smart_long_test.sh"
      backup: true
      mode: 0540

  - name: schedule weekly smart LONG test 
    become: true      
    ansible.builtin.cron:
      name: "check dirs"
      minute: "55"
      hour: "23"
      weekday: 6 # saturday
      job: 
        "{{script_location}}/ans_smart_long_test.sh"
      cron_file: ansible_weekly_smart_test
      user: root

  - name: copy script to mail disk report
    become: true
    template:
      src: ../templates/scripts/disk_report.j2
      dest: "{{script_location}}/ans_disk_report.py"
      backup: true
      mode: 0540

  - name: schedule weekly disk report
    become: true      
    ansible.builtin.cron:
      name: "check dirs"
      minute: "55"
      hour: "17"
      weekday: 0 # sunday
      job: 
        "{{script_location}}/ans_smart_long_test.sh"
      cron_file: ansible_weekly_smart_test
      user: root