- hosts: myvhosts
  vars_files:
    - ../../vars.json
  tasks:
  - name: Add the user magic
    become: true  
    ansible.builtin.user:
      name: "{{vmagic}}"
      comment: magic docker user
      uid: 1050
      group: docker
  
  - name: Copy the Dockerfile
    become: true
    become_user: "{{vmagic}}"
    template:
      src: ../../templates/rails/Dockerfile
      dest: "/home/{{ vmagic }}/Dockerfile"
      backup: true
      mode: 0640

  - name: Copy application files
    become: true
    become_user: "{{vmagic}}"
    copy:
      src: /home/yell/gits/Ansible/templates/rails/magic/
      dest: "/home/{{ vmagic }}/magic"
      backup: false
      mode: 0640


  - name: build container image
    become: true
    become_user: "{{vmagic}}"
    docker_image:
      name: magic:v1.0
      source: build
      build:
        path: "/home/{{ vmagic }}"
      state: present

  - name: Create a network net_magic
    become: true
    become_user: "{{vmagic}}"
    docker_network:
      name: net_magic

  - name: Add a container to a network
    become: true
    become_user: "{{vmagic}}"
    docker_network:
      name: net_magic
      connected:
        - proxy
        - nginx_web_1
  
