- hosts: myvhosts
  vars_files:
    - ../vars/samba.yml
    - ../vars.json


  tasks:  
  - name: get the username running the deploy
    become: false
    local_action: command whoami
    register: username_on_the_host

  
  - debug: var={{ansible_user_id}}