- hosts: myvhosts
  vars_files:
    - "{{ansible_vault}}/vars.yml"
#    - ../vars/samba.yml
 #   - ../vars/vars.yml


  tasks:  
  
  - debug: var=app_nginx.docker_compose_target

  - name: Create symbolic link 
    become: true
    file:
      src:  "{{zfs.pool_mountpoint}}/docker/syncthing/data"
      dest: "{{zfs.pool_mountpoint}}/samba/syncthing"
      state: link