- hosts: myvhosts
  vars_files:
    - ../vars/samba.yml
  tasks:  
    - name: Restoring nextcloud data
      become: true
      environment: 
        BORG_PASSCOMMAND: cat "/etc/.borg_password.key"
      ansible.builtin.shell:
        cmd: borg list --sort timestamp   repo  | grep -v '\.checkpoint$' | tail -1 |  cut -f 1 | cut -d ' ' -f 1
      args:
        chdir: /media/backup
      register: version

    - name: my debug
      debug:
        msg:         "returned value is {{version.stdout_lines}}"

    - name: Restoring nextcloud data
      become: true
      environment: 
        BORG_PASSCOMMAND: cat "/etc/.borg_password.key"
      ansible.builtin.shell:
        cmd: "borg extract /media/backup/repo::{{version.stdout_lines.0}} /home/nextcloud"
      args:
        chdir: /media/backup/c