- hosts: myvhosts
  vars_files:
    - ../vars/samba.yml
  tasks:  
    - name: Add the users to  group sambabackup
      become: true  
      ansible.builtin.user:
        name: myuser
        groups: "{{ item }}"
        append: yes
      with_items:
        - myuser
        -  adm
        - cdrom 
        - sudo
        - dip 
        - plugdev
        -  lxd
        - sambashare