- hosts: myvhosts
  vars_files:
    - "{{ansible_vault}}/vars.yml"
#    - ../vars/samba.yml
 #   - ../vars/vars.yml


  tasks:  
  
  - debug: var=app_nginx.docker_compose_target


  - name: copy script to check the recent borg backups
    become: true
    template:
      src: ../templates/scripts/disk_report.j2
      dest: "{{script_location}}/ans_disk_report.py"
      backup: true
      mode: 0540