# following https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04
- hosts: myvhosts
  become: true

  tasks:  
  - name: install packages
    ansible.builtin.include_tasks:
      file: ../tasks/010_install_packages.yml