- hosts: myvhosts
  vars_files:
    - ../vars/vars.yml
  vars:
    zfs_pool_state: present
    zfs_O_options: ## encryption options
      - "encryption=on"
      - "keyformat=raw"
      - "keylocation=file://{{zfs.key_location}}"
    zfs_pool_options:
      - "ashift=12"
      - "feature@encryption=enabled"
  vars_prompt:
    - name: "setup_zfs"
      prompt: "Did you check this file manually? (yes/no) "
    - name: "create_zfs"
      prompt: "Create a seperate zfs for nextcloud and mount it to /home/{{usersnames.nextcloud}} (yes/no)?"

## zfs key creation
## dd if=/dev/urandom of=zfs_key bs=32 count=1

  tasks:  
  - name: Setup ZFS
    ansible.builtin.include_tasks:
      file: ../tasks/017_setup_zfs.yml