- hosts: myvhosts
  vars_files:
    - ../vars.json
  tasks:
  - name: Add the user nextcloud
    become: true  
    ansible.builtin.user:
      name: "{{vnextcloud}}"
      comment: nextcloud docker user
      uid: 1041
      group: docker
  
      
  - name: Create a network net_nextcloud
    become: true
    become_user: "{{vnextcloud}}"
    docker_network:
      name: net_nextcloud

  - name: Add a container to a network
    become: true
    become_user: "{{vnextcloud}}"
    docker_network:
      name: net_nextcloud
      connected:
        - proxy
        - nginx_web_1
  

  - name: Ensure docker compose config in place
    become: true
    become_user: "{{vnextcloud}}"
    template:
      src: ../templates/nextcloud_docker_compose.j2
      dest: "{{ vnextcloud_compose }}"
      backup: true
      mode: 0640

  - name: deploy Docker Compose stack
    become: true
    become_user: "{{vnextcloud}}"
    community.docker.docker_compose:
      project_src: /home/{{vnextcloud}}
      files:
      - docker-compose.yml 

  - name: Ensure the database backup script is inplace
    become: true
    become_user: "{{vnextcloud}}"
    template:
      src: ../templates/nextcloud_db_backup.j2
      dest: "/home/{{ vnextcloud}}/db_backup.sh"
      backup: true
      mode: 0750

  - name: schedule a database backup every night
    become: true      
    ansible.builtin.cron:
      name: "check dirs"
      minute: "0"
      hour: "3"
      job: "/home/{{ vnextcloud}}/db_backup.sh"
      cron_file: ansible_nextcloud
      user: root