- hosts: myvhosts
  vars_files:
    - ../vars.json
  tasks:  
    - name: create folders
      become: true
      ansible.builtin.file:
        path: "/etc/borgmatic"
        state: directory
        mode: 600

    - name: Ensure group {{vbackup_group}} exists
      become: true
      ansible.builtin.group:
        name: "{{vbackup_group}}"
        state: present

    - name: create folders {{vborgmatic_backup_target}}
      become: true
      ansible.builtin.file:
        path: "{{vborgmatic_backup_target}}"
        state: directory
        owner: root
        group: "{{vbackup_group}}"
        mode: 750

    - name: add user {{vbackup_user}} to {{vbackup_group}}
      become: true  
      ansible.builtin.user:
        name: "{{vbackup_user}}"
        groups: "{{vbackup_group}}"
        append: yes


    - name: Ensure borgmatic config in place
      become: true
      template:
        src: ../templates/borgmatic_config.j2
        dest: "/etc/borgmatic/config.yaml"
        backup: true
        mode: 0640

    - name: Initialize an empty borg repository
      become: true      
      command: "borgmatic init --encryption repokey"

    - name: schedule borgmatic every night
      become: true      
      ansible.builtin.cron:
        name: "check dirs"
        minute: "00"
        hour: "4"
        job: "/usr/local/bin/borgmatic"
        cron_file: ansible_borgmatic
        user: root
        
    - name: provide borg password file
      become: true
      template:
        src: ../templates/borg_password.j2
        dest: "/etc/.borg_password.key"
        backup: true
        mode: 0400
