- hosts: myvhosts
  vars_files:
    - ../vars/vars.yml
    - ../vars/samba.yml
  tasks:  
     - name: Install and enable samba
       ansible.builtin.include_tasks:
        file: ../tasks/200_install_samba.yml