- name: check if the directory exists
  hosts: myvhosts
  vars_files:
  - ../vars.json
  become: false

  tasks:
    - name: Check if the directory exists
      ansible.builtin.stat:
        path: "{{ item.src }}"
      register: "dir_to_check"

    
      ansible.builtin.debug:
        msg: "Directory {{ item.src }} present"
      when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir"
      loop:
      - {src: "/home/{{vnextcloud}}"}