- hosts: myvhosts
  vars_files:
    - "{{ansible_vault}}/vars.yml"


  tasks:  
  - name: Install NGINX
    ansible.builtin.include_tasks:
      file: ../tasks/020_install_nginx.yml  


  - name: Install Pihole
    ansible.builtin.include_tasks:
      file: ../tasks/025_install_pihole.yml  
    when: "{{app_pihole.using}}"

  - name: Install portainer
    ansible.builtin.include_tasks:
      file: ../tasks/026_install_portainer.yml
    when: "{{app_portainer.using}}"

  - name: Install Bookstack docker
    ansible.builtin.include_tasks:
      file: ../tasks/030_install_bookstack.yml
    when: "{{app_bookstack.using}}"

  - name: Install Nextcloud docker
    ansible.builtin.include_tasks:
      file: ../tasks/040_install_nextcloud.yml
    when: "{{app_nextcloud.using}}"

  - name: Install syncthing docker
    ansible.builtin.include_tasks:
      file: ../tasks/050_install_syncthing.yml
    when: "{{app_syncthing.using}}"


  - name: Enable Borgmatic
    ansible.builtin.include_tasks:
      file: ../tasks/100_enable_borgmatic.yml
    when: "{{borgmatic.using}}"

  - name: Setup Email
    ansible.builtin.include_tasks:
      file: ../tasks/119_setup_email.yml


  - name: Setup hdd S.M.A.R.T reports
    ansible.builtin.include_tasks:
      file: ../tasks/120_hdd_logging.yml  

  - name: Install and enable samba
    ansible.builtin.include_tasks:
      file: ../tasks/200_install_samba.yml

 