- hosts: myvhosts
  vars_files:
    - ../vars.json
  tasks:


  - name: Ensure nginx config in place
    become: yes
    become_user: "{{vnginx}}"
    template:
      src: ../templates/nginx_conf.j2
      dest: "{{ vnginx_conf }}"
      backup: true
      mode: 0640

  - name: Ensure nginx nextcloud config in place
    become: yes
    become_user: "{{vnginx}}"
    template:
      src: ../templates/nginx_nextcloud_conf.j2
      dest: "{{ vnginx_nextcloud_conf }}"
      backup: true
      mode: 0640

  - name: deploy Docker Compose stack
    become: yes
    become_user: "{{vnginx}}"
    community.docker.docker_compose:
      project_src: /home/{{vnginx}}
      files:
      - docker-compose.yml 